#
# Docker compose config building perfsonar test environment
# with minimum one toolkit-server and one testpoint.
#
#   - No of probe nodes my be scaled up via 'docker-compose up --scale testpoint=<num>' with <num> = [1-10]
#     * When no of testpoint is >1 a star-topology is implemented ala
#
#      toolkit --- toolkit-net--- netem --- testpoint-net ---- testpoint_1
#                      |                          |    | `---- testpoint_2
#                      `------- docker host ------'    |           : 
#                                   |                  `------ testpoint_<num>
#                                Internet  
#
#     * netem adds routes in toolkit and testpoints containers to enable traffic to flow between toolkit and testpoints via netem
#     * netem also adds traffic impairments (i.e. loss and delay) on the path between testpoints and toolkit
#                                      
#   - OS distribution may be change by setting OS=ubuntu (e.g. 'OS=ubuntu docker-compose build')
#     
# Author: Otto J Wittner <otto.wittner@sikt.no>
# Date: 2022-09-02

#version: "3.7"
version: "3"

services:
  toolkit:
    container_name: ps-toolkit
    depends_on:
      - systemd-image
    image: ottojwittner/microdep-in-perfsonar_toolkit
    build:
      context: .
      dockerfile: ${OS:-centos}/Dockerfile
      args:
        TYPE: toolkit 
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # Make opensearch data persist over "reboots"
      #    NOTE: If enabled, run `sed -i 's/kirk/admin|/g' /securityadmin_demo.sh && /securityadmin_demo.sh` in toolkit container
      #          to update opensearch credentials
#      - opensearch:/var/lib/opensearch     
      # Add current dir as volum
      - .:/root/ps-dev
    tmpfs: 
      - /run
      - /tmp
    tty: true
    ports:
#      - 80:80    # http-access
#      - 443:443   # https-access
      - 8085:80    # http-access
      - 4435:443   # https-access
#      - 5601:5601  # Opensearch Dashboard (Kibana)
      - 5611:5601  # Opensearch Dashboard (Kibana)
      - 3000:3000  # Grafana
      - 861:861    # owamp control
      - 8760-8800:8760-8800 # owamp tests
      - 862:862    # twamp control
      - 18760-18800 # twamp tests
      - 5000:5000  # nuttcp
      - 5101:5101  # nuttcp
      - 5201:5201  # iperf3
      - 5001:5001  # iperf2
      - 1123:123   # ntp
    networks:
      toolkit-net:
        ipv4_address: 172.150.1.2

  testpoint:
    container_name: ps-testpoint
    depends_on:
      - systemd-image
#      - toolkit
    image: ottojwittner/microdep-in-perfsonar_testpoint
    build:
      context: .
      dockerfile: ${OS:-centos}/Dockerfile
      args:
        TYPE: testpoint 
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - testpoint-net
#    network_mode: host 

  systemd-image:
    image: ottojwittner/microdep-in-perfsonar_systemd-image
    build:
      context: .
      dockerfile: ${OS:-centos}/Dockerfile-systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # Just make image "die" as it is only a parent image  
    entrypoint: ["echo", "Service systemd-image only provides base image. See docker-compose.yml."]

  net-emulator:
    container_name: ps-netemulator
    depends_on:
      - testpoint
      - toolkit
    image: ottojwittner/microdep-in-perfsonar_net-emulator
    build:
      context: .
      dockerfile: netem/Dockerfile
    privileged: true     # Required (unfortunately) to enable network "hacking"
    volumes:
      - /proc:/proc
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      testpoint-net:
        ipv4_address: 172.150.2.200
      toolkit-net:
        ipv4_address: 172.150.1.200
        
networks:
  testpoint-net:
    ipam:
      driver: default
      config:
        # To match ips given in psconfig files
        - subnet: 172.150.2.0/24
          
  toolkit-net:
    ipam:
      driver: default
      config:
        # To match ips given in psconfig files
        - subnet: 172.150.1.0/24

volumes:
  opensearch:
