#
# Docker compose config building perfsonar test environment
# with minimum one toolkit-server and one testpoint.
#
# No of probe nodes my be scaled up via 'docker-compose up --scale testpoint=<num>'
#

version: "3.7"

services:
  toolkit:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TYPE: toolkit 
    privileged: true
#    cap_add:
#      - SYS_ADMIN
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
#    environment:
#      - container=docker
    ports:
      - 8085:80
    networks:
      - perfsonar-net
    #stop_grace_period: 20s

  testpoint:
    depends_on:
      - toolkit
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TYPE: testpoint 
#    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    networks:
      - perfsonar-net
    #stop_grace_period: 20s

networks:
  perfsonar-net:      
