#
# Docker compose config building perfsonar test environment
# with minimum one toolkit-server and one testpoint.
#
# No of probe nodes my be scaled up via 'docker-compose up --scale testpoint=<num>'
#

version: "3.7"

services:
  toolkit:
    hostname: ps-toolkit
    depends_on:
      - systemd-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TYPE: toolkit 
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      #- 8085:80
      - 80:80
      - 443:443
    networks:
      - perfsonar-net
    #  - dhcp
    #stop_grace_period: 20s

  testpoint:
    hostname: ps-testpoint
    depends_on:
      - systemd-image
      - toolkit
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TYPE: testpoint 
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - perfsonar-net
      #- dhcp
      
  systemd-image:
    build:
      context: .
      dockerfile: Dockerfile-systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - perfsonar-net

networks:
  perfsonar-net:      
  dhcp:
    #driver: ghcr.io/devplayer0/docker-net-dhcp:release-linux-amd64
    driver: ghcr.io/devplayer0/docker-net-dhcp:golang
    driver_opts:
      bridge: ps-bridge
      #ipv6: 'true'
      ignore_conflicts: 'false'
      skip_routes: 'false'
      #lease_timeout: '60s'
    ipam:
      driver: 'null'
