#
# Docker compose config building perfsonar test environment
# with minimum one toolkit-server and one testpoint.
#
#   - No of probe nodes my be scaled up via 'docker-compose up --scale testpoint=<num>' with <num> = [1-10]
#     * When no of testpoint is >1 a star-topology is implemented ala
#
#      toolkit --- toolkit-net--- netem --- testpoint-net ---- testpoint_1
#                      |                          |    | `---- testpoint_2
#                      `------- docker host ------'    |           : 
#                                                      `------ testpoint_<num>
#
#     * netem adds routes in toolkit and testpoints containers to enable traffic to flow between toolkit and testpoints via netem
#     * netem also adds traffic impairments (i.e. loss and delay) on the path between testpoints and toolkit
#                                      
#   - OS distribution may be change by setting OS=ubuntu (e.g. 'OS=ubuntu docker-compose build')
#     
# Author: Otto J Wittner <otto.wittner@sikt.no>
# Date: 2022-09-02

#version: "3.7"
#version: "3"
version: "2.4"

services:
  toolkit:
    hostname: ps-toolkit
    depends_on:
      - systemd-image
    build:
      context: .
      dockerfile: ${OS:-centos}/Dockerfile
      args:
        TYPE: toolkit 
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # Make misc data persist over "reboots"
      - opensearch:/var/lib/opensearch
#      - opensearch-ps-etc:/etc/perfsonar/opensearch
      - grafana:/var/lib/grafana
#      - etc:/etc
      # Add current dir as volum
      #- .:/root/ps-dev
      - /home/oak:/home/oak
    tmpfs: 
      - /run
      - /tmp
    tty: true
    #network_mode: host
    #    ports:
#      - 8085:80
#      - 4435:443   # For https-access
#      - 5611:5601  # Opensearch Dashboard (Kibana)
#      - 3000:3000  # Grafana
#      - 861:861    # owamp control
#      - 862:862    # twamp control
#      - 5000:5000  # nuttcp
#      - 5101:5101  # nuttcp
#      - 5201:5201  # iperf3
#      - 5001:5001  # iperf2
#      - 1123:123   # ntp
    networks:
      ps-sis-net: 
        ipv4_address: 158.38.2.234         
#      toolkit-net:
#        ipv4_address: 172.150.1.2

  testpoint:
    entrypoint: ["echo", "Service testpoint disabled. See docker-compose.yml."]
    hostname: ps-testpoint
    depends_on:
      - systemd-image
      - toolkit
    build:
      context: .
      dockerfile: ${OS:-centos}/Dockerfile
      args:
        TYPE: testpoint 
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - testpoint-net
      
  systemd-image:
    build:
      context: .
      dockerfile: ${OS:-centos}/Dockerfile-systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # Just make image "die" as it is only a parent image  
    entrypoint: ["echo", "Service systemd-image only provides base image. See docker-compose.yml."]
    #command: "true"  

  net-emulator:
    entrypoint: ["echo", "Service net-emulator disabled. See docker-compose.yml."]
    hostname: ps-netemulator
    depends_on:
      - testpoint
      - toolkit
    build:
      context: .
      dockerfile: netem/Dockerfile
    privileged: true     # Required (unfortunately) to enable network "hacking"
    volumes:
      - /proc:/proc
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      testpoint-net:
        ipv4_address: 172.150.2.200
      toolkit-net:
        ipv4_address: 172.150.1.200
        
networks:
  testpoint-net:
    ipam:
      driver: default
      config:
        # To match ips given in psconfig files
        - subnet: 172.150.2.0/24
          
  toolkit-net:
    ipam:
      driver: default
      config:
        # To match ips given in psconfig files
        - subnet: 172.150.1.0/24

  ps-sis-net:
    name: ps-sis-net
    driver: macvlan
    driver_opts:
      parent: bond0
    ipam:
      config:
        - subnet: "158.38.2.0/24"
          ip_range: "158.38.2.234/32"
          gateway: "158.38.2.1"
    
volumes:
  opensearch:
  opensearch-ps-etc:
  grafana:
  etc:

