#
# Build rpm packages for specified distro. 
# Run with "DISTRO=<distro-tag> SPEC=<rpm-spec-file> docker-compose run".
# Default distro is alma9. Valied distro tags are: alma9 centos7
# Default rpm-spec-files are "SPEC/*-alma9.spec"
#     
# Author: Otto J Wittner <otto.wittner@sikt.no>
# Date: 2024-02-02

#version: "3.7"
#version: "3"
version: "2.2"

services:
  buildcontainer:
    # Basic container, extended by other services
    container_name: ps-rpmbuilder
    hostname: ps-rpmbuilder
    image: rpmbuild-${DISTRO:-alma9}
    build:
      context: .
      dockerfile: Dockerfile-${DISTRO:-alma9}
    volumes:
#      - ${BUILDROOT:-./}:/home/rpmbuilder/rpmbuild 
#      - ${SRCROOT:-../../}:/home/src
      - ./SPECS:/home/rpmbuilder/rpmbuild/SPECS 
      - ./SOURCES:/home/rpmbuilder/rpmbuild/SOURCES 
      - ./SRPMS:/home/rpmbuilder/rpmbuild/SRPMS 
      - ./RPMS:/home/rpmbuilder/rpmbuild/RPMS
#      - ../../:/home/src
#     Needs 2 levels up as long as rpmbuilds/ is a symlink to dev/builds/ (which docker-compose expands)
      - ../../:/home/src
      
  rpmbuild:
    # Builds rpm packages specified by SPEC env var, or all specs matching "SPECS/*-alma9.spec"
    extends: buildcontainer
    stdin_open: true
    tty: true
    entrypoint: ["/bin/build-spec", "/home/rpmbuilder/rpmbuild/${SPEC:-SPECS/*-alma9.spec}"]

  pypspec:
    # Generate a rpm spec for a pip-installable python packages specified in PYPACK
    extends: buildcontainer
    stdin_open: true
    tty: true
    entrypoint: ["/usr/local/bin/pyp2rpm", "-s","${PYPACK}"]
      
  shell:
    # Bash in build container
    extends: buildcontainer
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]

    
  testrun:
    # Test container for microdep
    container_name: ps-microdep
    hostname: ps-microdep
    build:
      context: .
      dockerfile: Dockerfile-testrun-${DISTRO:-alma9}
    ports:
      - 8086:80
      - 4436:443
