#
# Docker compose config building perfsonar test environment
# with minimum one toolkit-server and one testpoint.
#
#   - No of probe nodes my be scaled up via 'docker-compose up --scale testpoint=<num>' with <num> = [1-10]
#     * When no of testpoint is >1 a star-topology is implemented ala
#
#      toolkit --- toolkit-net--- netem --- testpoint-net ---- testpoint_1
#                      |                          |    | `---- testpoint_2
#                      `------- docker host ------'    |           : 
#                                   |                  `------ testpoint_<num>
#                                Internet  
#
#     * netem adds routes in toolkit and testpoints containers to enable traffic to flow between toolkit and testpoints via netem
#     * netem also adds traffic impairments (i.e. loss and delay) on the path between testpoints and toolkit
#                                      
#   - OS distribution may be changed (from default almalinux) by setting DISTRO=my-distro running e.g. 'DISTRO=ubuntu docker-compose build'
#     
# Author: Otto J Wittner <otto.wittner@sikt.no>
# Date: 2022-09-02

#version: "3.7"
#version: "3"
version: "2.2"

services:
  ps-toolkit:
    container_name: ps-toolkit
    hostname: ${TOOLKIT_HOSTNAME:-toolkit}
    image: ps-microdep-toolkit-${DISTRO:-alma}
    depends_on:
      - systemd-image
    build:
      context: .
      dockerfile: ${DISTRO:-alma}/Dockerfile
      args:
        TYPE: toolkit
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # Make misc data persist over "reboots"
      - opensearch:/var/lib/opensearch
      - grafana:/var/lib/grafana
      - microdep-map-db:/usr/lib/perfsonar/microdep-map/mp-dragonlab/etc/
      # Make opensearch data persist over "reboots"
      # Add current dir as volum
      #- .:/root/ps-dev
      - /home/oak:/home/oak
      - /home/wittner:/home/wittner
    tmpfs: 
      - /run
      - /tmp
    tty: true
    ports:
      - 80:80    # http-access
      - 443:443   # https-access
      - 5601:5601  # Opensearch Dashboard (Kibana)
      - 3000:3000  # Grafana
      - 861:861    # owamp control
      - 8760-8800:8760-8800 # owamp tests
      - 862:862    # twamp control
      - 18760-18800 # twamp tests
      - 5000:5000  # nuttcp
      - 5101:5101  # nuttcp
      - 5201:5201  # iperf3
      - 5001:5001  # iperf2
      - 1123:123   # ntp
    networks:
      ps-sis-net: 
        ipv4_address: 158.38.2.234         

  systemd-image:
    build:
      context: .
      dockerfile: ${DISTRO:-alma}/Dockerfile-systemd
    image: systemd-image-${DISTRO:-alma}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # Just make image "die" as it is only a parent image  
    entrypoint: ["echo", "Service systemd-image only provides base image. See docker-compose.yml."]

networks:
  ps-sis-net:
    name: ps-sis-net
    driver: macvlan
    driver_opts:
      parent: bond0
    ipam:
      config:
        - subnet: "158.38.2.0/24"
          ip_range: "158.38.2.234/32"
          gateway: "158.38.2.1"
    
volumes:
  opensearch:
    name: opensearch-${DISTRO:-alma}
  grafana:
    name: grafana-${DISTRO:-alma}
  microdep-map-db:
    name: microdep-map-db-${DISTRO:-alma}

